/// Winst- en verliesrekening in lang formaat: bedrag per rekening (kosten positief opgeslagen).
table FactWinstVerlies
	lineageTag: b8d9dbfb-bf41-4e1a-9731-35d629bb6f29

	column DatumKey
		dataType: int64
		isHidden
		lineageTag: 846b7da9-6ccf-4aa1-997c-a88a98ca6249
		summarizeBy: none
		sourceColumn: DatumKey

		annotation SummarizationSetBy = User

	column ScenarioKey
		dataType: int64
		isHidden
		lineageTag: 2ab96b23-7015-4baa-bd57-7d84190b6fd2
		summarizeBy: none
		sourceColumn: ScenarioKey

		annotation SummarizationSetBy = User

	column RekeningKey
		dataType: int64
		isHidden
		lineageTag: 7376809b-644d-41ab-994a-79a16c29f92e
		summarizeBy: none
		sourceColumn: RekeningKey

		annotation SummarizationSetBy = User

	column Bedrag
		dataType: double
		formatString: #,0
		lineageTag: ee38e244-175a-4d95-b063-fb681bf79495
		summarizeBy: sum
		sourceColumn: Bedrag

		annotation SummarizationSetBy = User

	partition FactWinstVerlies = m
		mode: import
		source =
			let
			    Bron = Csv.Document(File.Contents(CsvMap & "FactWinstVerlies.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars=true]),
			    Typen = Table.TransformColumnTypes(Kop, {{"DatumKey", Int64.Type}, {"ScenarioKey", Int64.Type}, {"RekeningKey", Int64.Type}, {"Bedrag", type number}}, "en-US")
			in
			    Typen

	annotation PBI_ResultType = Table
