/// Kasstroomoverzicht per maand in lang formaat (indirecte methode).
table FactKasstroom
	lineageTag: 6469083d-c2c0-4984-bed0-e2a77ba0dcac

	column DatumKey
		dataType: int64
		isHidden
		lineageTag: e32ecfff-67c2-4a17-bbb2-ef9b8c62f5f3
		summarizeBy: none
		sourceColumn: DatumKey

		annotation SummarizationSetBy = User

	column ScenarioKey
		dataType: int64
		isHidden
		lineageTag: 236f92b2-84c1-4c6b-aa17-13b400dc64c7
		summarizeBy: none
		sourceColumn: ScenarioKey

		annotation SummarizationSetBy = User

	column Kasstroompost
		dataType: string
		lineageTag: 20eb7ccb-51e6-4168-a304-ead6b76a8be2
		summarizeBy: none
		sourceColumn: Kasstroompost

		annotation SummarizationSetBy = User

	column Bedrag
		dataType: double
		formatString: #,0
		lineageTag: 87cc1629-7046-446f-83c2-6eda40014bdd
		summarizeBy: sum
		sourceColumn: Bedrag

		annotation SummarizationSetBy = User

	partition FactKasstroom = m
		mode: import
		source =
			let
			    Bron = Csv.Document(File.Contents(CsvMap & "FactKasstroom.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars=true]),
			    Typen = Table.TransformColumnTypes(Kop, {{"DatumKey", Int64.Type}, {"ScenarioKey", Int64.Type}, {"Kasstroompost", type text}, {"Bedrag", type number}}, "en-US")
			in
			    Typen

	annotation PBI_ResultType = Table
