/// FTE per afdeling per maand.
table FactFTE
	lineageTag: bd29ae6b-98fc-44f9-859d-20e6df622051

	column DatumKey
		dataType: int64
		isHidden
		lineageTag: 05cd3db2-3ba1-454c-abca-63f9a08582fa
		summarizeBy: none
		sourceColumn: DatumKey

		annotation SummarizationSetBy = User

	column ScenarioKey
		dataType: int64
		isHidden
		lineageTag: 335ca57c-ec86-472e-b386-e9f4ed643eb5
		summarizeBy: none
		sourceColumn: ScenarioKey

		annotation SummarizationSetBy = User

	column AfdelingKey
		dataType: int64
		isHidden
		lineageTag: fad88c4c-d509-45d0-a9ff-1c563cfcc5c9
		summarizeBy: none
		sourceColumn: AfdelingKey

		annotation SummarizationSetBy = User

	column FTE
		dataType: double
		formatString: #,0.0
		lineageTag: 5a3f0673-8736-431d-9034-1f2196930973
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = User

	partition FactFTE = m
		mode: import
		source =
			let
			    Bron = Csv.Document(File.Contents(CsvMap & "FactFTE.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars=true]),
			    Typen = Table.TransformColumnTypes(Kop, {{"DatumKey", Int64.Type}, {"ScenarioKey", Int64.Type}, {"AfdelingKey", Int64.Type}, {"FTE", type number}}, "en-US")
			in
			    Typen

	annotation PBI_ResultType = Table
