/// Verklarende gebeurtenissen (storyline) met toelichting.
table Gebeurtenissen
	lineageTag: e0830e4d-d38a-41ec-88fa-da12a17bfc75

	/// Sleutel naar DimDatum (yyyymmdd, eerste dag van de maand).
	column DatumKey
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 928905bf-8639-4de1-a633-957726aa8faf
		summarizeBy: none
		sourceColumn: DatumKey

		annotation SummarizationSetBy = User

	/// Korte titel van de gebeurtenis.
	column Titel
		dataType: string
		lineageTag: 7499ac12-f5f0-4810-9dc7-43bc62e887e9
		summarizeBy: none
		sourceColumn: Titel

		annotation SummarizationSetBy = User

	/// Soort gebeurtenis: Marge, Financiering, Eenmalig of Groei.
	column Soort
		dataType: string
		lineageTag: f29fcfbb-3856-42c9-ae01-6a442791652e
		summarizeBy: none
		sourceColumn: Soort

		annotation SummarizationSetBy = User

	/// Toelichting op de gebeurtenis.
	column Toelichting
		dataType: string
		lineageTag: ca41ad5f-e448-4e1f-9df5-5e5e2a118ad3
		summarizeBy: none
		sourceColumn: Toelichting

		annotation SummarizationSetBy = User

	partition Gebeurtenissen = m
		mode: import
		source =
				let
				    Bron = Csv.Document(File.Contents(CsvMap & "Gebeurtenissen.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars=true]),
				    Typen = Table.TransformColumnTypes(Kop, {{"DatumKey", Int64.Type}, {"Titel", type text}, {"Soort", type text}, {"Toelichting", type text}}, "en-US"),
				    Binnen = Table.SelectRows(Typen, each [DatumKey] >= 20230101 and [DatumKey] <= 20291231),
				    Soort = Table.TransformColumns(Binnen, {{"Soort", each Record.FieldOrDefault([margin = "Marge", financing = "Financiering", oneoff = "Eenmalig", growth = "Groei"], _, _), type text}})
				in
				    Soort

	annotation PBI_ResultType = Table
